# Normalization pipeline, step by step

This notebook runs `src/pipeline/build.py` one step at a time, so each step can be shown and explained.
For a normal rebuild just run, from the project root:

```
python -m src.pipeline.build
```

| Step | Module | What it does |
|---|---|---|
| 1. adapters | `src/pipeline/adapters/` | one loader per chain: raw columns → common columns (and fixes known collector bugs) |
| 2. standardize | `src/pipeline/standardize.py`, `units.py`, `text.py` | units, pack sizes, € per kg/l/unit, clean names, brands |
| 3. quality | `standardize.py`, `build.py` | flags instead of deleting rows |
| 4. classify | `src/pipeline/classify.py` | product type per product, by text similarity to the taxonomy |
| 5. store | `src/pipeline/db.py` | SQLite `data/supermarkets.db` + `data/products_normalized.csv` |

In [2]:
import sys
from pathlib import Path

ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "src" / "pipeline").exists())
sys.path.insert(0, str(ROOT))

import pandas as pd
from src.pipeline import config
from src.pipeline.build import prepare, build, format_report
from src.pipeline.classify import decide, find_similar
from src.pipeline.evaluate import evaluate, load_labels, sample_for_labelling

## Steps 1–3: load every chain, standardize, first flags

`prepare()` runs the adapters, `standardize()` and picks the vectorizer (cached embeddings if available,
otherwise TF-IDF). Nothing is dropped: a product without a price per unit gets `flag_missing_ppu`.

In [3]:
p = prepare()
print("Vectorizer:", p["report"]["method"], *p["report"]["warnings"], sep="\n")
print(len(p["products"]), "products,", len(p["hits"]), "search hits")
p["observations"][["price_per_unit", "unit", "ppu_source", "flag_missing_ppu"]].describe(include="all")

Vectorizer:
tfidf
WARNING: embeddings unavailable for 11946 texts → whole run used TF-IDF (install requirements-embeddings.txt and rebuild)
13253 products, 12295 search hits

        price_per_unit   unit ppu_source flag_missing_ppu
count     13078.000000  13078      13078            13253
unique             NaN     11          2                2
top                NaN   KILO       site            False
freq               NaN   8444      12925            13078
mean         15.907452    NaN        NaN              NaN
std         168.063787    NaN        NaN              NaN
min           0.003000    NaN        NaN              NaN
25%           2.400000    NaN        NaN              NaN
50%           6.041000    NaN        NaN              NaN
75%          13.000000    NaN        NaN              NaN
max       11980.000000    NaN        NaN              NaN

In [4]:
# One product per chain, after standardization
p["products"].groupby("chain_id").head(1)[["product_key", "name", "name_clean", "brand", "is_private_label",
                                            "pack_count", "unit_quantity", "quantity_unit"]]

,product_key,name,name_clean,brand,is_private_label,pack_count,unit_quantity,quantity_unit
0,dia:504P6,Leche semidesnatada Dia Láctea pack 6 x 1 L,leche semidesnatada lactea pack,Dia,True,6.0,1.0,LITRO
918,mercadona:4241,"Aceite de oliva 0,4º Hacendado",aceite de oliva 0 4o,Hacendado,True,1.0,5.0,LITRO
5206,aldi:872200,Leche entera sin lactosa,leche entera sin lactosa,Milsani,True,1.0,1.0,LITRO
6067,alcampo:54180,AUCHAN Leche semidesnatada de vaca 6 x 1l Prod...,leche semidesnatada de vaca,Alcampo,True,6.0,1.0,LITRO
6763,ahorramas:70865,Leche Alipende 1l semidesnatada,leche semidesnatada,Alipende,True,1.0,1.0,LITRO
7156,bm:76411,Leche entera 1 l,leche entera,Bm,True,1.0,1.0,LITRO
10300,consum:7080604,Leche Semidesnatada Brik,leche semidesnatada brik,Consum,True,1.0,1.0,LITRO

## Step 4: classify

Each product is compared only with the types of the search terms that returned it
(`data/taxonomy/product_types.csv`). The closest one wins, unless it is a "noise" description,
the chain's category is excluded (pets, cosmetics…), or the score is below τ → `no_relevante`.

In [5]:
thresholds = config.THRESHOLDS[p["vectorizer"].method]
classification = decide(p["products"], p["hits"], p["taxonomy"], p["vectorizer"], thresholds)
print("tau/delta:", thresholds)
classification["method"].value_counts()

tau/delta: {'tau': 0.15, 'delta': 0.02}

method
tfidf                 9810
unclassified          2431
category_exclusion    1012
Name: count, dtype: int64

In [6]:
# Examples per type: does it look right?
examples = classification.merge(p["products"][["product_key", "name", "chain_id"]], on="product_key")
examples[examples["type_id"].isin(["leche_semidesnatada", "no_relevante"])].groupby("type_id").head(8)[
    ["chain_id", "name", "type_id", "score", "runner_up_type_id"]]

,chain_id,name,type_id,score,runner_up_type_id
0,dia,Leche semidesnatada Dia Láctea pack 6 x 1 L,leche_semidesnatada,0.794002,leche_desnatada
3,dia,Leche semidesnatada sin lactosa Dia Láctea pac...,leche_semidesnatada,0.645069,leche_sin_lactosa
4,dia,Leche semidesnatada Dia Láctea 1 L,leche_semidesnatada,0.840426,leche_desnatada
8,dia,Leche semidesnatada sin lactosa Dia Láctea 1 L,leche_semidesnatada,0.669231,leche_sin_lactosa
10,dia,Leche semidesnatada Asturiana pack 6 x 1 L,leche_semidesnatada,0.706348,leche_desnatada
15,dia,Leche semidesnatada Dia Láctea botella 1.5 L,leche_semidesnatada,0.745971,leche_desnatada
18,dia,Batido de cacao 90% leche Dia Láctea 6 x 200 ml,no_relevante,0.262958,leche_sin_lactosa
19,dia,Leche semidesnatada sin lactosa Asturiana pack...,leche_semidesnatada,0.624141,leche_sin_lactosa
20,dia,Leche semidesnatada Asturiana pack 6 x 1.5 L,leche_semidesnatada,0.706348,leche_desnatada
27,dia,Nata para cocinar textura espesa Dia Láctea 50...,no_relevante,0.100517,leche_sin_lactosa
35,dia,Leche condensada Dia Láctea 450 g,no_relevante,0.265695,leche_sin_lactosa
36,dia,Arroz con leche Dia Caprichoso 4 x 125 g,no_relevante,0.175052,arroz_integral
37,dia,Leche condensada Dia Láctea 1 Kg,no_relevante,0.265695,leche_sin_lactosa
38,dia,Nata para cocinar 18% M.G. Dia Láctea 3 x 200 ml,no_relevante,0.118374,leche_sin_lactosa
40,dia,Mousse de chocolate con leche Dia Caprichoso 4...,no_relevante,0.136934,leche_entera
41,dia,Galletas cubiertas de chocolate con leche Gall...,no_relevante,0.118767,leche_entera

## Step 5: build the database and the CSV

`build()` repeats the steps above and also adds `flag_outlier` (price per unit far from its type's usual range)
and `flag_unit_mismatch`, then writes `data/supermarkets.db` and `data/products_normalized.csv`.

In [7]:
print(format_report(build()))

WARNING: embeddings unavailable for 11946 texts → whole run used TF-IDF (install requirements-embeddings.txt and rebuild)
Classifier: tfidf (tfidf-char-3-5)
chain        rows  products  %€/unit  %no_rel %low_conf  error
dia          1161       918    100.0     48.6       3.5
mercadona    4621      4288    100.0     71.1       2.6
aldi         1076       861     91.2     54.5       3.1
alcampo       711       696     96.3     15.5       6.9
ahorramas     398       393     82.4     18.6       6.1
bm           4076      3144     99.9     56.8       2.3
consum       3873      2953    100.0     55.0       2.5

## Hand labelling (≈ 100 products, 30–40 min)

The cell below shows 100 products (5 per search term, spread across chains), each with the classifier's guess.
For each one type:

- **Enter** → the guess is right
- **a number** → pick that type from the list
- **n** → `no_relevante` (not really the product searched for)
- **q** → stop (answers are saved after each product; run the cell again to continue)

Answers go to `data/labels/hand_labels.csv`.

In [8]:
labels = load_labels()
done = set(labels["product_key"])
to_label = sample_for_labelling(p["products"], p["hits"], classification, labelled=set(), per_term=5)
to_label = to_label[~to_label["product_key"].isin(done)]
real_types = p["taxonomy"][p["taxonomy"]["is_negative"] == 0]
print(f"{len(done)} labelled, {len(to_label)} to go")

for i, row in enumerate(to_label.itertuples(), 1):
    options = list(real_types.loc[real_types["search_term"] == row.search_term, "type_id"])
    print(f"\n[{i}/{len(to_label)}] {row.name}  ({row.chain_id}; {row.chain_category if pd.notna(row.chain_category) else '-'})")
    print("  search term:", row.search_term, "| guess:", row.prefilled_type_id)
    print("  " + "  ".join(f"{k}) {t}" for k, t in enumerate(options, 1)) + "  n) no_relevante")
    answer = input("Enter = guess, number, n, q: ").strip().lower()
    if answer == "q":
        break
    if answer == "":
        chosen = row.prefilled_type_id if pd.notna(row.prefilled_type_id) else config.NO_RELEVANTE
    elif answer == "n":
        chosen = config.NO_RELEVANTE
    elif answer.isdigit() and 1 <= int(answer) <= len(options):
        chosen = options[int(answer) - 1]
    else:
        print("  ? not understood, skipped (it will come back next run)")
        continue
    new = pd.DataFrame([{"product_key": row.product_key, "type_id": chosen,
                         "prefilled_type_id": row.prefilled_type_id, "confirmed": 1}])
    new.to_csv(config.LABELS_PATH, mode="a", header=not config.LABELS_PATH.exists() or config.LABELS_PATH.stat().st_size == 0,
               index=False, encoding="utf-8")

1 labelled, 99 to go

[1/99] Chocolate con leche sin azúcar 100 gr  (bm; Chocolate con leche)
  search term: leche | guess: no_relevante
  1) leche_entera  2) leche_semidesnatada  3) leche_desnatada  4) leche_sin_lactosa  5) bebida_vegetal  n) no_relevante

[2/99] Natillas de chocolate Dia Caprichoso 4 x 125 g  (dia; -)
  search term: leche | guess: no_relevante
  1) leche_entera  2) leche_semidesnatada  3) leche_desnatada  4) leche_sin_lactosa  5) bebida_vegetal  n) no_relevante

[3/99] Leche semidesnatada Hacendado  (mercadona; Huevos, leche y mantequilla > Leche y bebidas vegetales > Leche semidesnatada)
  search term: leche | guess: leche_semidesnatada
  1) leche_entera  2) leche_semidesnatada  3) leche_desnatada  4) leche_sin_lactosa  5) bebida_vegetal  n) no_relevante

[4/99] AMBROSI Queso rallado Grana Padano 60 g.  (alcampo; -)
  search term: queso | guess: queso_rallado
  1) queso_curado  2) queso_tierno_fresco  3) queso_lonchas  4) queso_rallado  5) queso_untar  n) no_relevante

[5/99] Aceite de coco virgen Hacendado  (mercadona; Aceite, especias y salsas > Aceite, vinagre y sal > Otros aceites)
  search term: aceite | guess: aceite_oliva_virgen_extra
  1) aceite_oliva_virgen_extra  2) aceite_oliva  3) aceite_girasol  n) no_relevante
  ? not understood, skipped (it will come back next run)

[6/99] Agua de colonia bebé Nenuco  (mercadona; Bebé > Higiene y cuidado > Colonia)
  search term: agua | guess: no_relevante
  1) agua_sin_gas  2) agua_con_gas  n) no_relevante

[7/99] Espirales Alipende 500g con vegetales  (ahorramas; -)
  search term: pasta | guess: no_relevante
  1) pasta_larga  2) pasta_corta  3) pasta_integral  4) pasta_fresca_rellena  n) no_relevante
  ? not understood, skipped (it will come back next run)

[8/99] LA ESPAÑOLA Aceite de oliva suave lata de 5 l.  (alcampo; -)
  search term: aceite | guess: aceite_oliva
  1) aceite_oliva_virgen_extra  2) aceite_oliva  3) aceite_girasol  n) no_relevante

[9/99] Bagel clásico 4 unidades  (bm; Pan de molde blanco)
  search term: pan | guess: pan_molde
  1) pan_barra  2) pan_molde  3) pan_tostado  4) pan_hogaza  n) no_relevante

[10/99] Agua mineral Monte Pinos pack 6 x 1,5 L  (dia; -)
  search term: agua | guess: agua_con_gas
  1) agua_sin_gas  2) agua_con_gas  n) no_relevante

[11/99] Alas Partidas Pollo Certificado  (consum; Aves)
  search term: pollo | guess: pollo_alas
  1) pollo_pechuga  2) pollo_muslos  3) pollo_alas  4) pollo_entero  n) no_relevante

[12/99] Atún claro en escabeche Dia Mari Marinera 6 x 60 g  (dia; -)
  search term: atún | guess: no_relevante
  1) atun_aceite_oliva  2) atun_aceite_girasol  3) atun_natural  4) bonito_norte  n) no_relevante

[13/99] Molinillo 5 Bayas Tarro  (consum; Especias)
  search term: aceite | guess: no_relevante
  1) aceite_oliva_virgen_extra  2) aceite_oliva  3) aceite_girasol  n) no_relevante

[14/99] Salchichas Frankfurt sabor Ahumado  (consum; Salchichas)
  search term: salmón | guess: salmon_ahumado
  1) salmon_fresco  2) salmon_ahumado  n) no_relevante
  ? not understood, skipped (it will come back next run)

[15/99] Leche Hidratante  (consum; Cremas, lociones y colonia)
  search term: leche | guess: no_relevante
  1) leche_entera  2) leche_semidesnatada  3) leche_desnatada  4) leche_sin_lactosa  5) bebida_vegetal  n) no_relevante

[16/99] Postre de Soja Skyr Sabor Fresa  (consum; Yogur vegetal)
  search term: huevos | guess: yogur_vegetal
  1) huevos_gallina  2) huevos_camperos_eco  n) no_relevante

[17/99] Muffins de vainilla con pepitas de chocolate  (aldi; -)
  search term: pan | guess: no_relevante
  1) pan_barra  2) pan_molde  3) pan_tostado  4) pan_hogaza  n) no_relevante

[18/99] Alubia morada 1 kg  (bm; Secas)
  search term: arroz | guess: no_relevante
  1) arroz_redondo  2) arroz_largo  3) arroz_integral  4) arroz_vasito  n) no_relevante

[19/99] Detergente Fusión Floral 36+12 lavados  (bm; Máquina pastillas/cápsulas)
  search term: detergente | guess: detergente_capsulas
  1) detergente_liquido  2) detergente_capsulas  3) detergente_polvo  4) detergente_delicadas  n) no_relevante

[20/99] Sardina en aceite de oliva 120 g  (bm; Sardinas)
  search term: aceite | guess: no_relevante
  1) aceite_oliva_virgen_extra  2) aceite_oliva  3) aceite_girasol  n) no_relevante

[21/99] Barra Integral 100%  (consum; Pan Integral y otras semillas)
  search term: pan | guess: pan_molde
  1) pan_barra  2) pan_molde  3) pan_tostado  4) pan_hogaza  n) no_relevante

[22/99] ALCAMPO ECOLÓGICO Garbanzo Pedrosillano ecológico 500 g.  (alcampo; -)
  search term: garbanzos | guess: garbanzo_seco
  1) garbanzo_seco  2) garbanzo_cocido  n) no_relevante

[23/99] Queso pecorino toscano DOP al corte  (bm; Denominación de origen)
  search term: queso | guess: no_relevante
  1) queso_curado  2) queso_tierno_fresco  3) queso_lonchas  4) queso_rallado  5) queso_untar  n) no_relevante

[24/99] Galleta fina chocolate 126 g  (bm; Galletas de chocolate y rellenas)
  search term: pasta | guess: no_relevante
  1) pasta_larga  2) pasta_corta  3) pasta_integral  4) pasta_fresca_rellena  n) no_relevante

[25/99] Rodajas de atún de aleta amarilla Hacendado congelado  (mercadona; Congelados > Pescado > Pescado)
  search term: atún | guess: no_relevante
  1) atun_aceite_oliva  2) atun_aceite_girasol  3) atun_natural  4) bonito_norte  n) no_relevante

[26/99] Pechuga certificada extrafina bandeja (500g aprox)  (bm; Envasado)
  search term: pollo | guess: pollo_pechuga
  1) pollo_pechuga  2) pollo_muslos  3) pollo_alas  4) pollo_entero  n) no_relevante

[27/99] DANONE Yogur con sabor a coco, elaborado con leche fresca de vaca 4 x 120 g.  (alcampo; -)
  search term: yogur | guess: yogur_sabores
  1) yogur_natural  2) yogur_sabores  3) yogur_griego  4) yogur_bifidus  5) yogur_proteico  6) yogur_vegetal  n) no_relevante

[28/99] Comida con salmón fresco, frutas y verduras perro adulto Supreme Compy  (mercadona; Mascotas > Perro > Alimentación seca)
  search term: salmón | guess: no_relevante
  1) salmon_fresco  2) salmon_ahumado  n) no_relevante

[29/99] Pan moño  (mercadona; Panadería y pastelería > Pan de horno > Barra de pan)
  search term: pan | guess: pan_barra
  1) pan_barra  2) pan_molde  3) pan_tostado  4) pan_hogaza  n) no_relevante

[30/99] Bebida Refrescante Tinto Uva y Manzana  (consum; Mosto)
  search term: manzana | guess: manzana_roja
  1) manzana_roja  2) manzana_verde_amarilla  n) no_relevante

[31/99] Pasta fresca rellena de jamón  (aldi; -)
  search term: pasta | guess: pasta_fresca_rellena
  1) pasta_larga  2) pasta_corta  3) pasta_integral  4) pasta_fresca_rellena  n) no_relevante

[32/99] Alcohol De Cannabis Spray  (consum; Alcohol, agua oxigenada y otros)
  search term: agua | guess: no_relevante
  1) agua_sin_gas  2) agua_con_gas  n) no_relevante

[33/99] Zumo de manzana Hacendado  (mercadona; Zumos > Tomate y otros sabores > Otros sabores)
  search term: manzana | guess: no_relevante
  1) manzana_roja  2) manzana_verde_amarilla  n) no_relevante

[34/99] Dados de queso  (aldi; -)
  search term: queso | guess: queso_tierno_fresco
  1) queso_curado  2) queso_tierno_fresco  3) queso_lonchas  4) queso_rallado  5) queso_untar  n) no_relevante

[35/99] Uvas bandeja 400 g  (bm; Manzanas, peras y uvas)
  search term: manzana | guess: manzana_roja
  1) manzana_roja  2) manzana_verde_amarilla  n) no_relevante

[36/99] Arroz de Valencia Dacsa 1kg  (ahorramas; -)
  search term: arroz | guess: no_relevante
  1) arroz_redondo  2) arroz_largo  3) arroz_integral  4) arroz_vasito  n) no_relevante

[37/99] Masa de Pizza Finíssima Rectangular  (consum; Bases y masas)
  search term: arroz | guess: no_relevante
  1) arroz_redondo  2) arroz_largo  3) arroz_integral  4) arroz_vasito  n) no_relevante

[38/99] Shot Salud Digestiva  (consum; Zumos frescos)
  search term: zumo | guess: no_relevante
  1) zumo_naranja_exprimido  2) zumo_naranja  3) zumo_otras_frutas  4) nectar  n) no_relevante

[39/99] Lomo asado al horno  (aldi; -)
  search term: pollo | guess: no_relevante
  1) pollo_pechuga  2) pollo_muslos  3) pollo_alas  4) pollo_entero  n) no_relevante

[40/99] Yogur estilo griego Pastoret artesanal 500g  (ahorramas; -)
  search term: yogur | guess: yogur_griego
  1) yogur_natural  2) yogur_sabores  3) yogur_griego  4) yogur_bifidus  5) yogur_proteico  6) yogur_vegetal  n) no_relevante

[41/99] Yogur de proteínas sabor fresa y frambuesa 160 g  (bm; Yogur cremoso y enriquecido)
  search term: yogur | guess: yogur_sabores
  1) yogur_natural  2) yogur_sabores  3) yogur_griego  4) yogur_bifidus  5) yogur_proteico  6) yogur_vegetal  n) no_relevante

[42/99] BIFRUTAS Leche con zumo de frutas tropicales 1 l.  (alcampo; -)
  search term: zumo | guess: zumo_otras_frutas
  1) zumo_naranja_exprimido  2) zumo_naranja  3) zumo_otras_frutas  4) nectar  n) no_relevante

[43/99] Pizza Ristorante 4 Quesos  (consum; Pizza congelada)
  search term: queso | guess: no_relevante
  1) queso_curado  2) queso_tierno_fresco  3) queso_lonchas  4) queso_rallado  5) queso_untar  n) no_relevante

[44/99] FONT VELLA Agua mineral pack 4 uds. x 2,5 l.  (alcampo; -)
  search term: agua | guess: agua_con_gas
  1) agua_sin_gas  2) agua_con_gas  n) no_relevante

[45/99] Pate de Atún en Aceite Pack de 2 Latas  (consum; Paté pescado y marisco)
  search term: atún | guess: atun_aceite_oliva
  1) atun_aceite_oliva  2) atun_aceite_girasol  3) atun_natural  4) bonito_norte  n) no_relevante

[46/99] Ensalada de brotes tiernos  (aldi; -)
  search term: leche | guess: no_relevante
  1) leche_entera  2) leche_semidesnatada  3) leche_desnatada  4) leche_sin_lactosa  5) bebida_vegetal  n) no_relevante

[47/99] CAMPOS Atún claro en aceite de oliva 104 g.  (alcampo; -)
  search term: atún | guess: atun_aceite_oliva
  1) atun_aceite_oliva  2) atun_aceite_girasol  3) atun_natural  4) bonito_norte  n) no_relevante

[48/99] Bebida de pera 1 l  (bm; Zumos no refrigerados)
  search term: zumo | guess: zumo_naranja_exprimido
  1) zumo_naranja_exprimido  2) zumo_naranja  3) zumo_otras_frutas  4) nectar  n) no_relevante

[49/99] Comida para perro mini con salmón y pavo 4x100 g  (bm; Húmedo)
  search term: salmón | guess: no_relevante
  1) salmon_fresco  2) salmon_ahumado  n) no_relevante

[50/99] AOVE en spray  (aldi; -)
  search term: aceite | guess: no_relevante
  1) aceite_oliva_virgen_extra  2) aceite_oliva  3) aceite_girasol  n) no_relevante

[51/99] COLHOGAR Papel higiénico húmedo Pure 80 uds.  (alcampo; -)
  search term: papel higiénico | guess: papel_higienico_humedo
  1) papel_higienico  2) papel_higienico_humedo  n) no_relevante

[52/99] Burger meat de pavo con espinacas, elaboradas sin gluten ni lactosa  EL POZO King 2 x 120 g.  (alcampo; -)
  search term: carne picada | guess: hamburguesas
  1) picada_vacuno  2) picada_mixta  3) picada_pollo_pavo  4) hamburguesas  n) no_relevante

[53/99] Tomate triturado 660 g  (bm; Tomate)
  search term: tomate | guess: tomate_triturado
  1) tomate_fresco  2) tomate_cherry  3) tomate_triturado  4) tomate_frito  n) no_relevante

[54/99] Pastel de Crema 3 Unidades  (consum; Pastas de té)
  search term: pasta | guess: no_relevante
  1) pasta_larga  2) pasta_corta  3) pasta_integral  4) pasta_fresca_rellena  n) no_relevante

[55/99] HERO Solo Bio Tarritos de fruta (pera y manzana) ecológica, a partir de 4 meses 6 x 120 g  (alcampo; -)
  search term: manzana | guess: no_relevante
  1) manzana_roja  2) manzana_verde_amarilla  n) no_relevante

[56/99] Queso lonchas semicurado mezcla Hacendado  (mercadona; Charcutería y quesos > Queso lonchas, rallado y en porciones > Queso lonchas)
  search term: queso | guess: queso_lonchas
  1) queso_curado  2) queso_tierno_fresco  3) queso_lonchas  4) queso_rallado  5) queso_untar  n) no_relevante

[57/99] Tarrito Solo Eco Pera, Plátano y Zanahoria  (consum; Despensa)
  search term: plátano | guess: no_relevante
  1) platano_canarias  2) banana  n) no_relevante

[58/99] Burger meat de vacuno  (aldi; -)
  search term: carne picada | guess: hamburguesas
  1) picada_vacuno  2) picada_mixta  3) picada_pollo_pavo  4) hamburguesas  n) no_relevante

[59/99] Yogur griego con fresa Hacendado  (mercadona; Postres y yogures > Yogures griegos > Yogures griegos)
  search term: yogur | guess: yogur_griego
  1) yogur_natural  2) yogur_sabores  3) yogur_griego  4) yogur_bifidus  5) yogur_proteico  6) yogur_vegetal  n) no_relevante

[60/99] Tiras de pollo marinado empanadas chicken fries  (mercadona; Carne > Empanados y elaborados > Empanados y elaborados)
  search term: pollo | guess: no_relevante
  1) pollo_pechuga  2) pollo_muslos  3) pollo_alas  4) pollo_entero  n) no_relevante

[61/99] Tomate triturado Dia Vegecampo 800 g  (dia; -)
  search term: tomate | guess: tomate_triturado
  1) tomate_fresco  2) tomate_cherry  3) tomate_triturado  4) tomate_frito  n) no_relevante

[62/99] Agua Font Vella 50cl  (ahorramas; -)
  search term: agua | guess: agua_con_gas
  1) agua_sin_gas  2) agua_con_gas  n) no_relevante

[63/99] HERO Baby Tarrito de frutas variadas (pera, plátano, manzana, naranja...) a partir de 4 meses 4 x 190 g.  (alcampo; -)
  search term: plátano | guess: no_relevante
  1) platano_canarias  2) banana  n) no_relevante

[64/99] Tomate Aromito  (aldi; -)
  search term: tomate | guess: tomate_frito
  1) tomate_fresco  2) tomate_cherry  3) tomate_triturado  4) tomate_frito  n) no_relevante

[65/99] Detergente Líquido Adiós al Separar  (consum; A máquina líquido)
  search term: detergente | guess: detergente_liquido
  1) detergente_liquido  2) detergente_capsulas  3) detergente_polvo  4) detergente_delicadas  n) no_relevante

[66/99] Atún claro en aceite de oliva 195 g  (bm; Atún)
  search term: atún | guess: atun_aceite_oliva
  1) atun_aceite_oliva  2) atun_aceite_girasol  3) atun_natural  4) bonito_norte  n) no_relevante

[67/99] Tomate Frito Brik  (consum; Tomate frito)
  search term: tomate | guess: tomate_frito
  1) tomate_fresco  2) tomate_cherry  3) tomate_triturado  4) tomate_frito  n) no_relevante

[68/99] MARTIKO Salmón ahumado macerado 2x75 g.  (alcampo; -)
  search term: salmón | guess: salmon_ahumado
  1) salmon_fresco  2) salmon_ahumado  n) no_relevante

[69/99] ASEVI Detergente líquido para ropa de color 42 DS  (alcampo; -)
  search term: detergente | guess: detergente_delicadas
  1) detergente_liquido  2) detergente_capsulas  3) detergente_polvo  4) detergente_delicadas  n) no_relevante

[70/99] Pasta tiburón Hacendado  (mercadona; Arroz, legumbres y pasta > Pasta y fideos > Macarrones, pajaritas y hélices)
  search term: pasta | guess: pasta_corta
  1) pasta_larga  2) pasta_corta  3) pasta_integral  4) pasta_fresca_rellena  n) no_relevante

[71/99] Bolsita postre lácteo fresa y plátano Hacendado +8 meses  (mercadona; Bebé > Alimentación infantil > Yogures y postres)
  search term: plátano | guess: no_relevante
  1) platano_canarias  2) banana  n) no_relevante

[72/99] Arreglo de marisco pelado para arroz  (mercadona; Marisco y pescado > Marisco > Marisco)
  search term: arroz | guess: no_relevante
  1) arroz_redondo  2) arroz_largo  3) arroz_integral  4) arroz_vasito  n) no_relevante

[73/99] Actimel pack 6 sabor fresa plátano  (ahorramas; -)
  search term: plátano | guess: no_relevante
  1) platano_canarias  2) banana  n) no_relevante

[74/99] BIOGRAN Pan integral tipo payés 400 g.  (alcampo; -)
  search term: pan | guess: pan_molde
  1) pan_barra  2) pan_molde  3) pan_tostado  4) pan_hogaza  n) no_relevante

[75/99] Pollo asado troceado Bonchef 1,4 Kg aprox.  (dia; -)
  search term: pollo | guess: pollo_alas
  1) pollo_pechuga  2) pollo_muslos  3) pollo_alas  4) pollo_entero  n) no_relevante

[76/99] Garbanzos a la jardinera Hacendado  (mercadona; Pizzas y platos preparados > Platos preparados calientes > Platos de cuchara)
  search term: garbanzos | guess: no_relevante
  1) garbanzo_seco  2) garbanzo_cocido  n) no_relevante

[77/99] Burger crunchy de pollo con bacón y queso Selección de Dia 200 g  (dia; -)
  search term: carne picada | guess: hamburguesas
  1) picada_vacuno  2) picada_mixta  3) picada_pollo_pavo  4) hamburguesas  n) no_relevante

[78/99] Toallitas pack ahorro 4x52 unidades  (bm; Toallitas húmedas)
  search term: papel higiénico | guess: papel_higienico_humedo
  1) papel_higienico  2) papel_higienico_humedo  n) no_relevante

[79/99] Zumo de piña, manzana y uva  (aldi; -)
  search term: manzana | guess: manzana_roja
  1) manzana_roja  2) manzana_verde_amarilla  n) no_relevante

[80/99] Detergente Líquido Flota 42 + 10 Lavados Esencia  (ahorramas; -)
  search term: detergente | guess: detergente_liquido
  1) detergente_liquido  2) detergente_capsulas  3) detergente_polvo  4) detergente_delicadas  n) no_relevante

[81/99] Zumo Concentrado Alipende 1L Naranja-Mandarina  (ahorramas; -)
  search term: zumo | guess: zumo_naranja
  1) zumo_naranja_exprimido  2) zumo_naranja  3) zumo_otras_frutas  4) nectar  n) no_relevante

[82/99] Noodles de arroz Dia Selección Mundial 200 g  (dia; -)
  search term: arroz | guess: no_relevante
  1) arroz_redondo  2) arroz_largo  3) arroz_integral  4) arroz_vasito  n) no_relevante

[83/99] Garbanzos pedrosillano calidad extra producto de la marca Miau 1 kg  (ahorramas; -)
  search term: garbanzos | guess: garbanzo_seco
  1) garbanzo_seco  2) garbanzo_cocido  n) no_relevante

[84/99] Postre gelificado sabor fresa  (aldi; -)
  search term: huevos | guess: no_relevante
  1) huevos_gallina  2) huevos_camperos_eco  n) no_relevante

[85/99] Escalopines de salmón Selección de Dia 500 g aprox.  (dia; -)
  search term: salmón | guess: no_relevante
  1) salmon_fresco  2) salmon_ahumado  n) no_relevante

[86/99] Natilla con Galleta Tarrito  (consum; Yogures)
  search term: yogur | guess: yogur_natural
  1) yogur_natural  2) yogur_sabores  3) yogur_griego  4) yogur_bifidus  5) yogur_proteico  6) yogur_vegetal  n) no_relevante

[87/99] Amoníaco con detergente Bosque Verde  (mercadona; Limpieza y hogar > Lejía y líquidos fuertes > Amoníaco y salfumán)
  search term: detergente | guess: no_relevante
  1) detergente_liquido  2) detergente_capsulas  3) detergente_polvo  4) detergente_delicadas  n) no_relevante

[88/99] Guiso de Garbanzos con Espinacas  (consum; Preparados de verdura)
  search term: garbanzos | guess: no_relevante
  1) garbanzo_seco  2) garbanzo_cocido  n) no_relevante

[89/99] Zumo de plátano y maracuyá Dia Saborfera 1 L  (dia; -)
  search term: plátano | guess: no_relevante
  1) platano_canarias  2) banana  n) no_relevante

[90/99] Papel higiénico Lanta 12 rollos 3 capas perfumado  (ahorramas; -)
  search term: papel higiénico | guess: papel_higienico
  1) papel_higienico  2) papel_higienico_humedo  n) no_relevante

[91/99] Bebida de zumo de piña sin azúcares añadidos Dia Saborfera 1 L  (dia; -)
  search term: zumo | guess: no_relevante
  1) zumo_naranja_exprimido  2) zumo_naranja  3) zumo_otras_frutas  4) nectar  n) no_relevante

[92/99] Preparado de carne picada vacuno  (mercadona; Carne > Hamburguesas y picadas > Picadas y otros)
  search term: carne picada | guess: picada_mixta
  1) picada_vacuno  2) picada_mixta  3) picada_pollo_pavo  4) hamburguesas  n) no_relevante

[93/99] Preparado Picada de Cerdo  (consum; Picadas y hamburguesas)
  search term: carne picada | guess: picada_mixta
  1) picada_vacuno  2) picada_mixta  3) picada_pollo_pavo  4) hamburguesas  n) no_relevante

[94/99] Huevos grandes L  (mercadona; Huevos, leche y mantequilla > Huevos > Huevos)
  search term: huevos | guess: huevos_gallina
  1) huevos_gallina  2) huevos_camperos_eco  n) no_relevante

[95/99] Higiénico Húmedo Compacto  (consum; Toallitas húmedas)
  search term: papel higiénico | guess: papel_higienico_humedo
  1) papel_higienico  2) papel_higienico_humedo  n) no_relevante

[96/99] Tomate pera  (mercadona; Fruta y verdura > Verdura > Tomate)
  search term: tomate | guess: tomate_fresco
  1) tomate_fresco  2) tomate_cherry  3) tomate_triturado  4) tomate_frito  n) no_relevante

[97/99] Garbanzos cocidos ecológicos  (aldi; -)
  search term: garbanzos | guess: garbanzo_cocido
  1) garbanzo_seco  2) garbanzo_cocido  n) no_relevante

[98/99] Papel higiénico húmedo aloe vera  (aldi; -)
  search term: papel higiénico | guess: papel_higienico_humedo
  1) papel_higienico  2) papel_higienico_humedo  n) no_relevante


## Evaluation: embeddings vs TF-IDF

Half of the labels tune τ (best macro-F1) and δ (the margin that best separates right from wrong guesses);
the other half measures accuracy. With ~50 test products the accuracy has a wide 95% interval: we report it.
Copy the tuned τ/δ into `config.THRESHOLDS` and rebuild.

In [9]:
labels = load_labels()
results = [evaluate(p, labels)]
if p["vectorizer"].method == "embedding":
    results.append(evaluate(prepare(force_tfidf=True), labels))

summary = pd.DataFrame([{
    "method": r["method"], "tau": r["tau"], "delta": r["delta"], "n_test": r["report"]["n"],
    "accuracy": r["report"]["accuracy"],
    "accuracy 95% CI": "{:.2f}–{:.2f}".format(*r["report"]["accuracy_ci95"]),
    "macro F1": r["report"]["macro_f1"],
    "relevant precision": r["report"]["relevant_precision"],
    "relevant recall": r["report"]["relevant_recall"],
} for r in results]).round(3)
for r in results:
    for problem in r["problems"]:
        print("label problem:", problem)
summary

,method,tau,delta,n_test,accuracy,accuracy 95% CI,macro F1,relevant precision,relevant recall
0,tfidf,0.16,0.015,49,0.816,0.69–0.90,0.652,0.933,0.903

In [10]:
# Confusion matrix (test half) of the first method
results[0]["report"]["confusion"]

predicted,aceite_oliva,agua_con_gas,atun_aceite_oliva,detergente_capsulas,detergente_delicadas,detergente_liquido,garbanzo_seco,hamburguesas,manzana_roja,no_relevante,...,pollo_pechuga,queso_lonchas,queso_tierno_fresco,salmon_ahumado,tomate_fresco,tomate_frito,tomate_triturado,yogur_griego,yogur_vegetal,zumo_naranja_exprimido
true,,,,,,,,,,,,,,,,,,,,,
aceite_oliva,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
agua_sin_gas,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
atun_aceite_oliva,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
atun_natural,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
detergente_capsulas,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
detergente_delicadas,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
detergente_liquido,0,0,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
garbanzo_seco,0,0,0,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hamburguesas,0,0,0,0,0,0,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
no_relevante,0,0,0,0,0,0,0,0,1,16,...,0,0,0,0,0,0,0,0,1,0
pan_hogaza,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
papel_higienico,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
papel_higienico_humedo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pasta_corta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
picada_mixta,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pollo_alas,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
pollo_pechuga,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
queso_lonchas,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
queso_rallado,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
queso_tierno_fresco,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
salmon_ahumado,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
salmon_fresco,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
tomate_fresco,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
tomate_frito,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
tomate_triturado,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
yogur_griego,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
zumo_otras_frutas,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## Similar-product search

`find_similar` returns the products closest to a product (or to any text), optionally in one chain or type.
`compare_types.ipynb` uses it to find each product's equivalent in other chains.

In [11]:
find_similar("leche semidesnatada", k=5, chain="aldi",
             products=p["products"], classification=classification, vectorizer=p["vectorizer"])

,product_key,name,chain_id,type_id,similarity
5254,aldi:600260000,Leche fresca semidesnatada,aldi,leche_semidesnatada,0.880712
5208,aldi:82000,Leche con calcio semidesnatada,aldi,leche_semidesnatada,0.804703
5209,aldi:81900,Leche semidesnatada sin lactosa,aldi,leche_semidesnatada,0.799934
5210,aldi:81000,Leche desnatada,aldi,leche_desnatada,0.727752
5266,aldi:45700,Leche desnatada sin lactosa,aldi,leche_sin_lactosa,0.529549